[package]
name = "rustc_llvm"
version = "0.0.0"
edition = "2021"

[features]
static-libstdcpp = []
emscripten = []

[dependencies]
libc = { path = "../../../libc" }

[build-dependencies]
cc = "1.0.69"
